#!/usr/bin/env ruby

# This script deploys this gem itself.

require "rubygems"
require "bundler"
Bundler.require(:default)

Upsteem::Deploy.deploy_gem(
  File.dirname(__FILE__), ARGV[0], ARGV[1],
  "config/deploy.yml"
)
